language: node_js
node_js:
  - "10"
  - "node"
branches:
  only:
    - master
before_install:
  - npm install -g
cache:
  directories:
  - node_modules/
before_script:
  - npm run compile
script:
  - npm run test
  - npm run check
